### ISSUE TITLE
Unable to create a new user account / You must enter a valid email address

### ISSUE THREAD

**Issue by ahrib** [idmarinas/lotgd-game#1342]
**Describe the bug**
Unable to create a new user account due to email being considered invalid. 

**To Reproduce**
1. Go to (https://lotgd.infommo.es/create.php?op=create)
2. Fill in user details, use a gmail.com or outlook.com or outlook.com.au email address
3. Click create your character
4. See error "You must enter a valid email address."

**Expected behavior**
No error for a valid email address

**Desktop**
 - OS: macos 12.4
 - Browser Chrome v103

**Comment by idmarinas** [comment]
Thx for your report, I'm cheking file for fix this bug.

**Comment by idmarinas** [comment]
Ok, this error are fixed in version 7.1.1

The online version has already been patched, so accounts can be created.

**Comment by ahrib** [comment]
Hi, while I can create an account & Email verification I think worked.. I am still facing multiple issues.

**Issue 1. Login - does not work**
* No error message shown on screen
* Additional notes:
I registered a user "strider009" however in the full list of warriors (https://lotgd.infommo.es/list.php?page=1&c=30) this was not there, but a user "strider" was present


**Issue 2. Forgot Password does not work** 
using username "strider009" I receive an error 
> Could not locate a character with that name. Look at the List Warriors page off the login page to make sure that the character hasn't expired and been deleted.

using username "strider" (see note in issue 1 above) I receive a forgot password email, however when clicking it I receive an error an message 
> Your request could not be verified. This may be because the link you used is invalid. Try to log in, and if that doesn't help, use the 'Forgotten Password' option to retrieve a new mail. In case of all hope lost, use the petition link at the bottom of the page and provide ALL details with what you did and what info you got.
